### ISSUE TITLE
OSPP项目咨询

### ISSUE THREAD

**Issue by AkaShark** [nebula-contrib/nebula-arkts#1]
Hi 老师好，我从OSPP的项目列表看到了我们的项目，我看到我们仓库中包含了很多其他语言的客户端，我想确定下我们这次OSPP的项目是否是想要提供一个Arkts的客户端可以方便用户在hopm仓库中下载使用。

**Comment by CorvusYe** [comment]
你好，有任何比较具体的问题都可以留言哈。

**Comment by AkaShark** [comment]
> 你好，有任何比较具体的问题都可以留言哈。

不好意思刚被其他事情block了下... 目前还没有什么具体的问题，我最近先把官方Thrift编译成TS来尝试下，到时候有具体问题我会在issues请教您哈

**Comment by CorvusYe** [comment]
> Hi 老师好，我从OSPP的项目列表看到了我们的项目，我看到我们仓库中包含了很多其他语言的客户端，我想确定下我们这次OSPP的项目是否是想要提供一个Arkts的客户端可以方便用户在hopm仓库中下载使用。

是的。很高兴你能对这个课题感兴趣。
这边有一个跟目标语言比较相近的项目，或许对课题可以有一些帮助。https://github.com/nebula-contrib/nebula-node
从你主页中也看到一些dart相关的项目，或许这个项目也可以给你提供参考: https://github.com/graph-cn/nebula_dart_gdbc

（ps: 称呼大叶就行，怎么简单怎么来😊）
